"""Research helpers for SKU deduplication experiments.

This package is intentionally independent from ``pipeline/`` and
``mpstats_app/``.  It is imported by research notebooks only.
"""

from .candidates import (
    CandidateGenerationConfig,
    add_cross_marketplace_flags,
    add_hard_negative_flags,
    add_pack_variant_flags,
    generate_candidate_pairs,
    prepare_product_records,
)
from .clustering import (
    FAMILY_EDGE_LABELS,
    PACK_EDGE_LABELS,
    ComponentConfig,
    PackSignatureConfig,
    add_component_flags,
    build_components,
    component_size_summary,
    same_pack_signature_mask,
)
from .embedding_candidates import (
    FAISS_CANDIDATE_OUTPUT_COLUMNS,
    FaissCandidateGenerationConfig,
    generate_faiss_candidate_pairs,
)
from .labeling import LabelingSamplingConfig, stratified_labeling_sample
from .fusion import FusionConfig, decide_label
from .model_registry import (
    CROSS_ENCODER_BACKEND,
    DEFAULT_POLZA_BASE_URL,
    EMBEDDING_BACKENDS,
    MODEL_CACHE_DIR_ENV,
    MODEL_LOCAL_ONLY_ENV,
    POLZA_AI_API_KEY_ENV,
    POLZA_API_KEY_ENV,
    POLZA_BASE_URL_ENV,
    POLZA_EMBEDDING_BACKEND,
    SENTENCE_TRANSFORMER_BACKEND,
    TRANSFORMERS_AUTO_MODEL_BACKEND,
    ModelManager,
    ModelSpec,
    PolzaEmbeddingModel,
    clear_model_pool,
    fetch_polza_models,
    get_model_cache_dir,
    get_polza_base_url,
    list_model_specs,
    model_pool_size,
    model_text_prefix,
    resolve_embedding_model_spec,
    resolve_model_spec,
)
from .matchers import (
    BiEncoderMatcher,
    CrossEncoderMatcher,
    JinaRerankerMatcher,
    MatcherStatus,
    PAIR_LABELS,
    PairMatcher,
    RuleBasedMatcher,
)
from .metrics import classification_report_df, confusion_matrix_df
from .normalization import (
    DEFAULT_FLAVOR_TOKENS,
    meaningful_title_tokens,
    normalize_brand,
    normalize_title,
    title_similarity,
    tokenize_title,
)
from .threshold_calibration import (
    ERROR_REPORT_COLUMNS,
    NEGATIVE_LABELS,
    POSITIVE_LABELS,
    TRIAGE_LABELS,
    CalibratedThresholds,
    ThresholdCalibrationConfig,
    apply_triage_predictions,
    auto_diff_threshold_grid,
    auto_same_threshold_grid,
    calibrate_and_evaluate_methods,
    calibrate_method_thresholds,
    error_report,
    forced_confusion_matrix,
    prepare_calibration_frame,
    same_base_product_from_labels,
    same_base_product_target,
    threshold_pair_review,
    triage_confusion_matrix,
    write_compact_threshold_report,
    write_threshold_reports,
)

__all__ = [
    "CandidateGenerationConfig",
    "BiEncoderMatcher",
    "CalibratedThresholds",
    "ComponentConfig",
    "CrossEncoderMatcher",
    "DEFAULT_POLZA_BASE_URL",
    "DEFAULT_FLAVOR_TOKENS",
    "EMBEDDING_BACKENDS",
    "ERROR_REPORT_COLUMNS",
    "FAMILY_EDGE_LABELS",
    "FAISS_CANDIDATE_OUTPUT_COLUMNS",
    "FusionConfig",
    "FaissCandidateGenerationConfig",
    "JinaRerankerMatcher",
    "LabelingSamplingConfig",
    "CROSS_ENCODER_BACKEND",
    "MODEL_CACHE_DIR_ENV",
    "MODEL_LOCAL_ONLY_ENV",
    "ModelManager",
    "ModelSpec",
    "NEGATIVE_LABELS",
    "POLZA_AI_API_KEY_ENV",
    "POLZA_API_KEY_ENV",
    "POLZA_BASE_URL_ENV",
    "POLZA_EMBEDDING_BACKEND",
    "POSITIVE_LABELS",
    "PolzaEmbeddingModel",
    "MatcherStatus",
    "PACK_EDGE_LABELS",
    "PackSignatureConfig",
    "PAIR_LABELS",
    "PairMatcher",
    "RuleBasedMatcher",
    "SENTENCE_TRANSFORMER_BACKEND",
    "TRANSFORMERS_AUTO_MODEL_BACKEND",
    "TRIAGE_LABELS",
    "ThresholdCalibrationConfig",
    "add_cross_marketplace_flags",
    "add_component_flags",
    "add_hard_negative_flags",
    "add_pack_variant_flags",
    "apply_triage_predictions",
    "auto_diff_threshold_grid",
    "auto_same_threshold_grid",
    "build_components",
    "calibrate_and_evaluate_methods",
    "calibrate_method_thresholds",
    "classification_report_df",
    "clear_model_pool",
    "confusion_matrix_df",
    "component_size_summary",
    "decide_label",
    "error_report",
    "fetch_polza_models",
    "forced_confusion_matrix",
    "generate_faiss_candidate_pairs",
    "generate_candidate_pairs",
    "get_model_cache_dir",
    "get_polza_base_url",
    "list_model_specs",
    "meaningful_title_tokens",
    "model_pool_size",
    "model_text_prefix",
    "normalize_brand",
    "normalize_title",
    "prepare_product_records",
    "prepare_calibration_frame",
    "resolve_embedding_model_spec",
    "resolve_model_spec",
    "same_pack_signature_mask",
    "same_base_product_from_labels",
    "same_base_product_target",
    "threshold_pair_review",
    "stratified_labeling_sample",
    "title_similarity",
    "triage_confusion_matrix",
    "tokenize_title",
    "write_compact_threshold_report",
    "write_threshold_reports",
]
