"""Research helpers for SKU deduplication experiments.

This package is intentionally independent from ``pipeline/`` and
``mpstats_app/``.  It is imported by research notebooks only.
"""

from .env import find_project_root, load_research_dotenv, parse_dotenv

load_research_dotenv()

from .candidates import (
    CandidateGenerationConfig,
    add_cross_marketplace_flags,
    add_hard_negative_flags,
    add_pack_variant_flags,
    generate_candidate_pairs,
    prepare_product_records,
)
from .category_runs import (
    DEDUP_CATEGORY_RUN_ENV,
    KNOWN_CATEGORY_RUNS,
    DedupCategoryRun,
    DedupRunPaths,
    available_category_run_names,
    resolve_category_run,
    resolve_run_paths,
)
from .clustering import (
    FAMILY_EDGE_LABELS,
    PACK_EDGE_LABELS,
    ComponentConfig,
    PackSignatureConfig,
    add_component_flags,
    build_components,
    component_size_summary,
    same_pack_signature_mask,
)
from .embedding_candidates import (
    FAISS_CANDIDATE_OUTPUT_COLUMNS,
    FaissCandidateGenerationConfig,
    generate_faiss_candidate_pairs,
)
from .labeling import (
    LabelingSamplingConfig,
    labeling_score_strata_masks,
    split_labeling_target_size,
    stratified_labeling_sample,
)
from .fusion import (
    FusionConfig,
    FusionRun,
    decide_label,
    prepare_fusion_pair_edges,
    select_fusion_run,
)
from .model_registry import (
    CROSS_ENCODER_BACKEND,
    DEFAULT_POLZA_BASE_URL,
    EMBEDDING_BACKENDS,
    MODEL_CACHE_DIR_ENV,
    MODEL_LOCAL_ONLY_ENV,
    POLZA_AI_API_KEY_ENV,
    POLZA_API_KEY_ENV,
    POLZA_BASE_URL_ENV,
    POLZA_EMBEDDING_BACKEND,
    SENTENCE_TRANSFORMER_BACKEND,
    TRANSFORMERS_AUTO_MODEL_BACKEND,
    ModelManager,
    ModelSpec,
    PolzaEmbeddingModel,
    clear_model_pool,
    fetch_polza_models,
    get_model_cache_dir,
    get_polza_base_url,
    list_model_specs,
    model_pool_size,
    model_text_prefix,
    resolve_embedding_model_spec,
    resolve_model_spec,
)
from .matchers import (
    BiEncoderMatcher,
    CrossEncoderMatcher,
    JinaRerankerMatcher,
    MatcherStatus,
    PAIR_LABELS,
    PairMatcher,
    RuleBasedMatcher,
)
from .metrics import classification_report_df, confusion_matrix_df
from .normalization import (
    DEFAULT_FLAVOR_TOKENS,
    meaningful_title_tokens,
    normalize_brand,
    normalize_title,
    title_similarity,
    tokenize_title,
)
from .threshold_calibration import (
    FN_COST,
    FP_COST,
    NEGATIVE_LABELS,
    POSITIVE_LABELS,
    SUMMARY_COLUMNS,
    UNIT_WEIGHT_FALLBACK_SOURCE,
    BinaryThresholdConfig,
    add_pair_weights,
    apply_binary_predictions,
    calibrate_and_evaluate_methods,
    detect_sales_volume_columns,
    prepare_calibration_frame,
    same_base_product_from_labels,
    same_base_product_target,
    summarize_by_volume_bucket,
    write_binary_threshold_reports,
    write_threshold_reports,
)

__all__ = [
    "CandidateGenerationConfig",
    "BiEncoderMatcher",
    "BinaryThresholdConfig",
    "ComponentConfig",
    "CrossEncoderMatcher",
    "DEDUP_CATEGORY_RUN_ENV",
    "DEFAULT_POLZA_BASE_URL",
    "DEFAULT_FLAVOR_TOKENS",
    "DedupCategoryRun",
    "DedupRunPaths",
    "EMBEDDING_BACKENDS",
    "FN_COST",
    "FP_COST",
    "FAMILY_EDGE_LABELS",
    "FAISS_CANDIDATE_OUTPUT_COLUMNS",
    "FusionConfig",
    "FusionRun",
    "FaissCandidateGenerationConfig",
    "JinaRerankerMatcher",
    "KNOWN_CATEGORY_RUNS",
    "LabelingSamplingConfig",
    "CROSS_ENCODER_BACKEND",
    "MODEL_CACHE_DIR_ENV",
    "MODEL_LOCAL_ONLY_ENV",
    "ModelManager",
    "ModelSpec",
    "NEGATIVE_LABELS",
    "POLZA_AI_API_KEY_ENV",
    "POLZA_API_KEY_ENV",
    "POLZA_BASE_URL_ENV",
    "POLZA_EMBEDDING_BACKEND",
    "POSITIVE_LABELS",
    "PolzaEmbeddingModel",
    "MatcherStatus",
    "PACK_EDGE_LABELS",
    "PackSignatureConfig",
    "PAIR_LABELS",
    "PairMatcher",
    "RuleBasedMatcher",
    "SENTENCE_TRANSFORMER_BACKEND",
    "TRANSFORMERS_AUTO_MODEL_BACKEND",
    "SUMMARY_COLUMNS",
    "UNIT_WEIGHT_FALLBACK_SOURCE",
    "add_cross_marketplace_flags",
    "add_component_flags",
    "add_hard_negative_flags",
    "add_pair_weights",
    "add_pack_variant_flags",
    "apply_binary_predictions",
    "available_category_run_names",
    "build_components",
    "calibrate_and_evaluate_methods",
    "classification_report_df",
    "clear_model_pool",
    "confusion_matrix_df",
    "component_size_summary",
    "decide_label",
    "detect_sales_volume_columns",
    "fetch_polza_models",
    "find_project_root",
    "generate_faiss_candidate_pairs",
    "generate_candidate_pairs",
    "get_model_cache_dir",
    "get_polza_base_url",
    "list_model_specs",
    "load_research_dotenv",
    "labeling_score_strata_masks",
    "meaningful_title_tokens",
    "model_pool_size",
    "model_text_prefix",
    "normalize_brand",
    "normalize_title",
    "prepare_product_records",
    "prepare_calibration_frame",
    "prepare_fusion_pair_edges",
    "parse_dotenv",
    "resolve_category_run",
    "resolve_embedding_model_spec",
    "resolve_model_spec",
    "resolve_run_paths",
    "same_pack_signature_mask",
    "same_base_product_from_labels",
    "same_base_product_target",
    "select_fusion_run",
    "split_labeling_target_size",
    "stratified_labeling_sample",
    "summarize_by_volume_bucket",
    "title_similarity",
    "tokenize_title",
    "write_binary_threshold_reports",
    "write_threshold_reports",
]
